name: chronos
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  # Python
  - python=3.11.13

  # Core libraries
  - numpy=2.1.3
  - pandas=2.3.1
  - scipy=1.16.1
  - matplotlib=3.10.3
  - scikit-learn=1.7.1

  # PyTorch
  - pytorch=2.7.1
  - torchaudio


  # Utilities
  - pip
  - pip:
      - torchvision==0.22.1
      - chronos-forecasting==1.5.2
      - plotly==6.2.0
      - optuna==4.4.0
      - ray==2.44.1
      - fastapi==0.116.1
      - uvicorn==0.35.0
      - xgboost==3.0.3
      - lightgbm==4.6.0
      - autogluon==1.4.0
      - mlforecast==0.14.0
      - statsforecast==2.0.1
